name: Release Package

on:
  # temporary
  push:
  release:
    types:
      - created

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_FILE: .config/docker/Dockerfile
  DOCKER_BUILD_PATH: .
  REGISTRY: ghcr.io
  OWNER: maxim-usikov
  IMAGE_NAME: hello-github-docker-action
  IMAGE_TAG: v1.0.0-beta.0

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: .bin/prepare_env.sh
        shell: bash

      - name: Build
        run: .bin/docker_build.sh
        shell: bash

      - name: Login
        run: .bin/docker_login.sh
        shell: bash

      - name: Push
        run: .bin/docker_push.sh
        shell: bash
