name: Release Package

on:
  # temporary
  push:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        env:
          DOCKER_FILE: ".config/docker/Dockerfile"
          DOCKER_BUILD_PATH: "."
        run: .bin/build_docker_image.sh
        shell: bash

  push-image:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: ghcr.io
          OWNER: maxim-usikov
        run: .bin/push_docker_image.sh
        shell: bash
