name: Release Package

on:
  # temporary
  push:
  release:
    types:
      - created

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_FILE: .config/docker/Dockerfile
  DOCKER_BUILD_PATH: .
  REGISTRY: ghcr.io
  OWNER: maxim-usikov
  IMAGE_NAME: hello-github-docker-action
  IMAGE_TAG: v1.0.0-beta.0


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: .bin/build_docker_image.sh
        shell: bash

  push-image:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push image
        run: .bin/push_docker_image.sh
        shell: bash
