name: Release Package

on:
  release:
    types:
      - created

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: .bin/prepare_env.sh
        shell: bash

      - name: Build
        run: .bin/docker_build.sh
        shell: bash

      - name: Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: .bin/docker_login.sh
        shell: bash

      - name: Push
        run: .bin/docker_push.sh
        shell: bash
