name: Release Package

on:
  # temporary
  push:
  release:
    types:
      - created

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: .bin/build_docker_image.sh
        shell: bash

  push-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push image
        run: .bin/push_docker_image.sh
        shell: bash
